version: '3.8'
services:
    dns-owl:
        image: ghcr.io/simonl169/dns-owl:latest
        ports:
            - 8000:8000
        environment:
            - TZ=Europe/Berlin
            - CRONVARS2=*/10 * * * *
        volumes:
            - ./config.json:/app/config.json
            
