version: '3.8'
services:
    dns-owl:
        image: ghcr.io/simonl169/dns-owl:v0.2
        environment:
            - TZ=Europe/Berlin
            - CRONVARS2=*/1 * * * *
        volumes:
            - ./config.json:/app/config.json
            
