name: Bump Version and Commit to main

on:
  workflow_dispatch:
    inputs:
      serverBump:
        description: 'Bump Script Version'
        required: true
        default: 'false'
        type: choice
        options:
          - 'False'
          - minor
          - patch
          - major


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-root
  cancel-in-progress: true

jobs:
  bump_version:
    runs-on: ubuntu-latest

    outputs:
      ref: ${{ steps.push-tag.outputs.commit_long_sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Bump version
        run: python test.py --server="${{ inputs.serverBump }}"

      - name: Commit and tag
        id: push-tag
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Simon_Bot
          message: 'Version ${{ env.NEXT_SERVER }}'
          tag: ${{ env.NEXT_SERVER }}
          push: true